# Starter pipeline

trigger: none

pool: DevSecops_Agent

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'DevSecOps_Federation'
    backendAzureRmResourceGroupName: 'Rishi_RG'
    backendAzureRmStorageAccountName: 'storage72111'
    backendAzureRmContainerName: 'terraformcontainer'
    backendAzureRmKey: 'Prode.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'DevSecOps_Federation'


