trigger:
- none

pool:
  name: DevSecops_Agent

stages:

# --------------------------
# Stage 1: Init + Validate + Plan
# --------------------------
- stage: Terraform_Preparation
  displayName: 'Terraform Init, Validate & Plan'
  jobs:
  - job: InitValidatePlan
    displayName: 'Init, Validate & Plan'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'Terraform Init (Stage 1)'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'DevSecOps_Federation'
        backendAzureRmResourceGroupName: 'Vaishanvi_RG'
        backendAzureRmStorageAccountName: 'vaishanvistorage'
        backendAzureRmContainerName: 'vaishanvicontainer'
        backendAzureRmKey: 'Prod.terraform.tfstate'
        commandOptions: '-reconfigure'

    - task: TerraformTask@5
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'DevSecOps_Federation'

# --------------------------
# Stage 2: Apply (with Init)
# --------------------------
- stage: Terraform_Apply
  displayName: 'Terraform Apply Stage'
  dependsOn: Terraform_Preparation
  condition: succeeded()
  jobs:
  - job: Apply
    displayName: 'Terraform Init & Apply'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'Terraform Init (Stage 2)'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'DevSecOps_Federation'
        backendAzureRmResourceGroupName: 'Vaishanvi_RG'
        backendAzureRmStorageAccountName: 'vaishanvistorage'
        backendAzureRmContainerName: 'vaishanvicontainer'
        backendAzureRmKey: 'Prod.terraform.tfstate'
        commandOptions: '-reconfigure'

    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'DevSecOps_Federation'
