trigger: none

pool:
  name: Devops_Pipline

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installation'
  inputs:
    terraformVersion: '1.8.2'  # Or use 'latest' if you prefer

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Federation_connection_pipeline'
    backendAzureRmResourceGroupName: 'Rishi_RG'
    backendAzureRmStorageAccountName: 'storage72111'
    backendAzureRmContainerName: 'terraformcontainer'  # ✅ Fixed spelling
    backendAzureRmKey: 'Prod.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    environmentServiceNameAzureRM: 'Federation_connection_pipeline'  # ✅ Added for auth

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Federation_connection_pipeline'  # ✅ Needed for auth
