trigger: none

pool:
  name: Devops_Pipline

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installation'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Login'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Federation_connection_pipeline'
    backendAzureRmResourceGroupName: 'Rishi_RG'
    backendAzureRmStorageAccountName: 'storage72111'
    backendAzureRmContainerName: 'terraformconatiner'
    backendAzureRmKey: 'Prod.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    backendServiceArm: 'Federation_connection_pipeline'

